import { ArrowRight, CheckCircle2, Fingerprint, LockKeyhole, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { demoUsers } from '../../data/mockUsers';
import { signIn } from '../../services/auth/authService';
import { Brand, Button } from '../../components/ui';

export function LoginPage() {
  const [role, setRole] = useState('Citizen');
  const [notice, setNotice] = useState('');
  const navigate = useNavigate();
  const enter = async () => { const user = await signIn(role); setNotice(`Demo access enabled for ${user.name}`); setTimeout(() => navigate(role === 'Citizen' ? '/citizen/dashboard' : '/officer/dashboard'), 300); };
  return <div className="auth-page"><aside className="auth-aside"><Brand /><div className="auth-aside-copy"><span className="eyebrow">ONE RECORD. MANY SERVICES.</span><h1>Land records,<br />connected.</h1><p>A unified view of land information and services for citizens and public officers.</p><div className="auth-trust"><span><ShieldCheck size={17} />Secure by design</span><span><Fingerprint size={17} />ULPIN-centric records</span></div></div><div className="auth-aside-foot"><span>BHARAT · JHARKHAND</span><span>SIH-26014 · PROTOTYPE</span></div><div className="auth-orb auth-orb-one" /><div className="auth-orb auth-orb-two" /></aside><main className="auth-main"><div className="auth-card"><div className="auth-mobile-brand"><Brand /></div><span className="eyebrow">WELCOME TO BHU SETU</span><h2>Sign in to your account</h2><p className="auth-subtitle">Choose a demo workspace to explore the prototype.</p><label className="form-field"><span>Workspace role</span><div className="role-options">{demoUsers.map((user) => <button key={user.role} type="button" onClick={() => setRole(user.role)} className={`role-option ${role === user.role ? 'role-selected' : ''}`}><span className="role-radio">{role === user.role && <i />}</span><span><strong>{user.role}</strong><small>{user.location}</small></span></button>)}</div></label><label className="form-field"><span>Email address</span><div className="input-icon"><Fingerprint size={16} /><input type="email" placeholder="name@example.gov.in" defaultValue="ananya.soren@example.in" /></div></label><label className="form-field"><span>Password</span><div className="input-icon"><LockKeyhole size={16} /><input type="password" placeholder="Enter your password" defaultValue="prototype" /><button type="button" className="input-trailing">Show</button></div></label><div className="auth-options"><label><input type="checkbox" defaultChecked /> Keep me signed in</label><a href="#help">Need help?</a></div>{notice && <div className="inline-success"><CheckCircle2 size={16} />{notice}</div>}<Button className="auth-submit" icon={ArrowRight} onClick={enter}>Continue to workspace</Button><div className="prototype-notice"><ShieldCheck size={16} /><span><strong>Prototype access</strong><small>This sign-in is for demonstration only. Credentials are not verified and no government system is connected.</small></span></div><div className="auth-register">New to Bhu Setu? <Link to="/register">Create an account <ArrowRight size={14} /></Link></div></div><div className="auth-legal">By continuing, you agree to the <a href="#terms">Terms of use</a> and <a href="#privacy">Privacy notice</a>.</div></main></div>;
}

export function RegisterPage() { return <div className="auth-page"><aside className="auth-aside"><Brand /><div className="auth-aside-copy"><span className="eyebrow">CITIZEN SERVICES</span><h1>Your land<br />services, together.</h1><p>Create a demo citizen profile to explore the Bhu Setu experience.</p></div><div className="auth-aside-foot"><span>BHARAT · JHARKHAND</span><span>SIH-26014 · PROTOTYPE</span></div></aside><main className="auth-main"><div className="auth-card"><div className="auth-mobile-brand"><Brand /></div><span className="eyebrow">GET STARTED</span><h2>Create your account</h2><p className="auth-subtitle">Registration is a visual prototype. Do not enter real personal information.</p><label className="form-field"><span>Full name</span><input className="input" placeholder="Enter your name" /></label><label className="form-field"><span>Email address</span><input className="input" placeholder="name@example.in" /></label><label className="form-field"><span>Mobile number</span><input className="input" placeholder="+91 00000 00000" /></label><label className="form-field"><span>District</span><select className="input"><option>Khunti</option><option>Ranchi</option><option>Gumla</option><option>Lohardaga</option></select></label><Button className="auth-submit" icon={ArrowRight}>Create demo profile</Button><div className="prototype-notice"><ShieldCheck size={16} /><span><strong>Prototype only</strong><small>Identity checks and secure account creation will be part of the future backend.</small></span></div><div className="auth-register">Already have access? <Link to="/login">Sign in <ArrowRight size={14} /></Link></div></div></main></div>; }
