import { ArrowRight, ArrowUpRight, Bell, BookOpenCheck, FilePlus2, FileText, Landmark, MapPinned, Search, ShieldCheck, Wallet } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { parcels } from '../../data/mockParcels';
import { applications, activity } from '../../data/mockApplications';
import { notifications } from '../../data/mockNotifications';
import { getCurrentUser } from '../../services/auth/authService';
import { Badge, Button, Card, SectionHeading, StatusBadge } from '../../components/ui';

export default function CitizenDashboard({ user = getCurrentUser() }) {
  const navigate = useNavigate();
  return <>
    <div className="welcome-banner"><div className="welcome-copy"><div className="welcome-kicker"><span className="live-dot" />CITIZEN LAND SERVICES <span className="welcome-date">· MONDAY, 29 SEPTEMBER 2026</span></div><h1>Good morning, {user?.name?.split(' ')[0] || 'Ananya'} <span>✦</span></h1><p>Your land records and service requests, all in one place.</p><div className="welcome-actions"><Button icon={Search} onClick={() => navigate('/search')}>Search a land record</Button><Button variant="light" icon={FilePlus2} onClick={() => navigate('/citizen/apply')}>Apply for a service</Button></div></div><div className="welcome-stamp"><span>MY LAND RECORDS</span><strong>02</strong><small>PARCELS LINKED</small></div></div>
    <div className="citizen-stat-grid"><Card className="citizen-stat"><span className="citizen-stat-icon icon-green"><MapPinned size={19} /></span><div><small>Land parcels</small><strong>02</strong><span>Ownership verified</span></div><ArrowUpRight size={16} /></Card><Card className="citizen-stat"><span className="citizen-stat-icon icon-blue"><ClipboardSymbol /></span><div><small>Applications</small><strong>02</strong><span>1 needs your attention</span></div><ArrowUpRight size={16} /></Card><Card className="citizen-stat"><span className="citizen-stat-icon icon-amber"><FileText size={18} /></span><div><small>Documents</small><strong>04</strong><span>All records in wallet</span></div><ArrowUpRight size={16} /></Card><Card className="citizen-stat"><span className="citizen-stat-icon icon-violet"><ShieldCheck size={18} /></span><div><small>Record health</small><strong>Good</strong><span>Last checked 24 Sep</span></div><ArrowUpRight size={16} /></Card></div>
    <div className="citizen-grid"><div className="citizen-main-column"><Card className="content-card"><SectionHeading eyebrow="YOUR LAND" title="Linked parcels" action={<Link className="text-link" to="/citizen/land">View all parcels <ArrowRight size={14} /></Link>} /><div className="parcel-list">{parcels.slice(0, 2).map((parcel, index) => <div className="citizen-parcel" key={parcel.ulpin}><div className={`parcel-thumb parcel-thumb-${index}`}><span className="parcel-thumb-grid" /><MapPinned size={17} /></div><div className="citizen-parcel-info"><div className="parcel-title-line"><strong>{parcel.location.split(',')[0]} parcel</strong><StatusBadge status={index ? 'Verified' : parcel.status} /></div><span className="mono-label">{parcel.ulpin}</span><div className="parcel-mini-meta"><span>{parcel.area} acres</span><i />{parcel.landType}<i />Survey {parcel.surveyNumber}</div></div><Link className="round-arrow" to={`/land/${parcel.ulpin}`} aria-label="Open parcel"><ArrowUpRight size={17} /></Link></div>)}</div></Card>
      <Card className="content-card"><SectionHeading eyebrow="IN PROGRESS" title="Recent applications" action={<Link className="text-link" to="/citizen/applications">All applications <ArrowRight size={14} /></Link>} /><div className="application-preview">{applications.slice(0, 2).map((application) => <Link to={`/citizen/applications/${application.id}`} className="application-preview-row" key={application.id}><span className="application-type-icon"><Landmark size={17} /></span><span className="application-preview-copy"><strong>{application.type} application</strong><small>{application.id} · {application.ulpin}</small></span><StatusBadge status={application.status} /><ArrowUpRight size={16} /></Link>)}</div></Card>
    </div><div className="citizen-side-column"><Card className="content-card"><SectionHeading eyebrow="SHORTCUTS" title="Quick services" /><div className="quick-action-grid"><QuickAction icon={Search} title="Search ULPIN" to="/search" /><QuickAction icon={Wallet} title="Land wallet" to="/citizen/wallet" /><QuickAction icon={FilePlus2} title="Mutation" to="/citizen/apply" /><QuickAction icon={Bell} title="Raise grievance" to="/citizen/grievances/new" /></div></Card><Card className="content-card"><SectionHeading eyebrow="RECENT UPDATES" title="Notifications" action={<Link className="icon-link" to="/notifications">See all</Link>} /><div className="citizen-notes">{notifications.slice(0, 3).map((note) => <div className="citizen-note" key={note.title}><span className={`note-mark note-${note.type}`} /><div><strong>{note.title}</strong><p>{note.message}</p><small>{note.time}</small></div>{note.unread && <i className="unread-dot" />}</div>)}</div></Card><Card className="help-card"><span className="help-icon"><BookOpenCheck size={19} /></span><div><strong>Need help with a service?</strong><p>Find guidance on land records and applications.</p><a href="#help">Browse citizen help <ArrowRight size={14} /></a></div></Card></div></div>
    <Card className="activity-strip"><div className="activity-strip-head"><span className="activity-symbol"><Landmark size={16} /></span><strong>Recent land activity</strong><span className="activity-muted">A clear history of recent actions on your records</span><Link to="/citizen/applications">View history <ArrowRight size={14} /></Link></div><div className="activity-strip-items">{activity.slice(0, 3).map((item) => <div className="activity-mini" key={item.title}><span className={`activity-dot dot-${item.tone}`} /><span><strong>{item.title}</strong><small>{item.detail}</small></span><time>{item.time}</time></div>)}</div></Card>
    <div className="citizen-disclaimer"><ShieldCheck size={15} />Your records are shown for demonstration. Production services would connect to authorized government data systems.</div>
  </>;
}

function QuickAction({ icon: Icon, title, to }) { return <Link to={to} className="quick-action"><span><Icon size={17} /></span><strong>{title}</strong><ArrowUpRight size={14} /></Link>; }
function ClipboardSymbol() { return <FileText size={18} />; }
