import { Activity, ArrowDownToLine, ArrowRight, ArrowUpRight, BadgeCheck, Building2, CalendarDays, ChevronRight, CircleAlert, FileCheck2, FileText, MapPin, MapPinned, MoreHorizontal, ShieldAlert, ShieldCheck, Sparkles, Trees, Wallet } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { getParcelByULPIN } from '../../services/land/landService';
import { parcels } from '../../data/mockParcels';
import { applications } from '../../data/mockApplications';
import { documents } from '../../data/mockDocuments';
import { Card, Badge, Button, RiskIndicator, SectionHeading, StatusBadge, Table } from '../../components/ui';

export default function LandProfilePage() {
  const { ulpin } = useParams();
  const parcel = getParcelByULPIN(ulpin) || parcels[0];
  const related = applications.filter((application) => application.ulpin === parcel.ulpin);
  const parcelDocs = documents.filter((document) => document.ulpin === parcel.ulpin);
  const transactions = [
    { id: 'TX-2025-084', date: '14 Mar 2025', type: 'Sale deed', parties: 'Previous holder → Current owner', value: '₹35,00,000', status: 'Registered' },
    { id: 'TX-2022-031', date: '08 Jun 2022', type: 'Inheritance', parties: 'Family transfer', value: 'Not applicable', status: 'Recorded' },
  ];
  const transactionColumns = [{ key: 'date', label: 'DATE' }, { key: 'type', label: 'TRANSACTION' }, { key: 'parties', label: 'PARTIES' }, { key: 'value', label: 'DECLARED VALUE' }, { key: 'status', label: 'STATUS', render: (value) => <StatusBadge status={value} /> }];
  return <><div className="profile-breadcrumb"><Link to="/search">Land search</Link><ChevronRight size={14} /><span>Land intelligence profile</span></div><div className="profile-hero"><div className="profile-hero-left"><div className="profile-hero-icon"><MapPinned size={22} /></div><div><span className="eyebrow">LAND INTELLIGENCE PROFILE <span className="sample-record">· FICTIONAL DEMO RECORD</span></span><h1>{parcel.ulpin}</h1><div className="profile-location"><MapPin size={14} />{parcel.location}<i />Survey No. {parcel.surveyNumber}</div></div></div><div className="profile-hero-actions"><Button variant="outline" icon={ArrowDownToLine}>Export profile</Button><Button icon={MoreHorizontal}>Actions</Button></div><div className="profile-summary-stats"><div><small>REGISTERED OWNER</small><strong>{parcel.owner}</strong><span><BadgeCheck size={14} /> Record holder</span></div><div><small>PARCEL AREA</small><strong>{parcel.area} <em>acres</em></strong><span>Survey {parcel.surveyNumber}</span></div><div><small>LAND CLASSIFICATION</small><strong>{parcel.landType}</strong><span>{parcel.currentUse} · Current use</span></div><div><small>REGISTERED VALUE</small><strong>{parcel.registeredValue}</strong><span>Latest recorded value</span></div></div></div>
    <div className="profile-alert-strip"><span className="alert-strip-icon"><ShieldAlert size={16} /></span><div><strong>AI-assisted risk indicator</strong><span>This prototype score is a review aid only. It is not a legal determination.</span></div><RiskIndicator value={parcel.riskScores.overall} compact /><button aria-label="Risk details"><ChevronRight size={17} /></button></div>
    <div className="profile-columns"><div className="profile-main-column"><Card className="content-card"><SectionHeading eyebrow="PARCEL RECORD" title="Overview" action={<Badge tone="green"><BadgeCheck size={13} /> Record current</Badge>} /><div className="overview-grid"><Info label="ULPIN" value={parcel.ulpin} mono /><Info label="Current owner" value={parcel.owner} /><Info label="Survey number" value={parcel.surveyNumber} /><Info label="Recorded area" value={`${parcel.area} acres`} /><Info label="Location" value={parcel.location} /><Info label="Land type" value={parcel.landType} /><Info label="Current land use" value={parcel.currentUse} /><Info label="Last record update" value="24 Sep 2026" /></div><div className="ror-row"><span className="ror-icon"><FileCheck2 size={17} /></span><div><strong>Record of Rights (RoR)</strong><small>Jamabandi reference · Circle Khunti · Register 14-B</small></div><StatusBadge status="Verified" /><Button variant="text" size="sm">View RoR <ArrowUpRight size={14} /></Button></div></Card>
      <Card className="content-card"><SectionHeading eyebrow="CHAIN OF TITLE" title="Ownership history" description="Recorded ownership changes for this parcel" action={<button className="icon-button"><MoreHorizontal size={17} /></button>} /><div className="ownership-timeline">{parcel.ownershipHistory.map((item, index) => <div className={`ownership-item ${index === parcel.ownershipHistory.length - 1 ? 'ownership-current' : ''}`} key={item.year}><div className="ownership-rail"><span>{index === parcel.ownershipHistory.length - 1 ? <BadgeCheck size={14} /> : <span />}</span>{index < parcel.ownershipHistory.length - 1 && <i />}</div><div className="ownership-body"><div><strong>{item.owner}</strong>{index === parcel.ownershipHistory.length - 1 && <Badge tone="green">CURRENT OWNER</Badge>}</div><span>{item.event}</span></div><time>{item.year}</time></div>)}</div></Card>
      <Card className="content-card"><SectionHeading eyebrow="REGISTERED ACTIVITY" title="Transaction history" action={<button className="text-link">Full history <ArrowRight size={14} /></button>} /><Table columns={transactionColumns} rows={transactions} /></Card>
      <Card className="content-card"><SectionHeading eyebrow="APPLICATION RECORD" title="Mutation history" /><div className="simple-timeline"><div><i className="timeline-green" /><span><strong>Ownership mutation recorded</strong><small>08 Jun 2022 · Application MU-2022-0381 · Completed</small></span><StatusBadge status="Approved" /></div><div><i className="timeline-amber" /><span><strong>Current mutation request</strong><small>24 Sep 2026 · {related[0]?.id || 'No active request'}</small></span><StatusBadge status={related[0]?.status || 'No active application'} /></div></div></Card>
    </div><div className="profile-side-column"><Card className="content-card risk-panel"><SectionHeading eyebrow="PROTOTYPE ANALYSIS" title="Risk indicators" /><div className="risk-panel-score"><RiskIndicator value={parcel.riskScores.overall} label="Overall indicator" /><span>Out of 100<br />Review priority: {parcel.riskScores.overall >= 65 ? 'Elevated' : parcel.riskScores.overall >= 40 ? 'Moderate' : 'Routine'}</span></div><div className="risk-breakdown">{Object.entries({ 'Document consistency': parcel.riskScores.document, 'Ownership chain': parcel.riskScores.ownership, 'Mutation activity': parcel.riskScores.mutation, 'Transaction pattern': parcel.riskScores.transaction, 'Encroachment signal': parcel.riskScores.encroachment }).map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}<small>/100</small></strong><i><b style={{ width: `${value}%` }} /></i></div>)}</div><div className="risk-note"><Sparkles size={15} /> AI-Assisted Risk Indicator — Prototype</div></Card>
      <Card className="content-card"><SectionHeading eyebrow="DOCUMENT REGISTER" title="Documents" action={<Link className="icon-link" to="/citizen/documents">View all</Link>} />{parcelDocs.length ? <div className="document-mini-list">{parcelDocs.map((document) => <div className="document-mini" key={document.name}><span><FileText size={16} /></span><div><strong>{document.type}</strong><small>{document.name}</small></div><StatusBadge status={document.status} /></div>)}</div> : <div className="document-mini"><span><FileText size={16} /></span><div><strong>Sale deed and RoR</strong><small>Records available in mock wallet</small></div></div>}<Link className="document-upload-link" to="/citizen/documents"><span>+ Add a document</span><ArrowRight size={14} /></Link></Card>
      <Card className="content-card"><SectionHeading eyebrow="LAND-USE OBSERVATIONS" title="Land-use analysis" /><div className="land-use-line"><span><Trees size={16} /></span><div><strong>Agriculture</strong><small>2022 · Baseline classification</small></div><Badge tone="green">STABLE</Badge></div><div className="land-use-line"><span><Building2 size={16} /></span><div><strong>{parcel.currentUse}</strong><small>2026 · Prototype layer classification</small></div><Badge tone="blue">CURRENT</Badge></div><div className="analysis-note"><Activity size={14} /> Imagery comparison is illustrative in this prototype.</div></Card>
      <Card className="content-card"><SectionHeading eyebrow="RELATED SERVICES" title="Applications & disputes" />{related.length ? related.map((application) => <Link className="related-row" to={`/citizen/applications/${application.id}`} key={application.id}><span><FileText size={16} /></span><div><strong>{application.type} · {application.id}</strong><small>Submitted {application.submitted}</small></div><StatusBadge status={application.status} /></Link>) : <p className="muted-copy">No active applications are linked in the demo data.</p>}<div className="encroachment-status"><CircleAlert size={15} /><span>Encroachment check<small>No confirmed determination · review required</small></span></div><Link to="/officer/disputes" className="small-inline-link">View related disputes <ArrowRight size={13} /></Link></Card></div></div><div className="profile-source-note"><ShieldCheck size={14} /> Prototype record assembled from fictional sample data. Source department data is not connected.</div></>;
}

function Info({ label, value, mono = false }) { return <div className="overview-field"><small>{label}</small><strong className={mono ? 'mono-label' : ''}>{value}</strong></div>; }
