import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

const landTypes = [{ name: 'Agricultural', value: 48, color: '#418b6d' }, { name: 'Residential', value: 27, color: '#608cad' }, { name: 'Commercial', value: 14, color: '#d39a48' }, { name: 'Other', value: 11, color: '#9e91bf' }];
const months = [{ month: 'Apr', submitted: 84, approved: 61 }, { month: 'May', submitted: 102, approved: 73 }, { month: 'Jun', submitted: 91, approved: 77 }, { month: 'Jul', submitted: 123, approved: 82 }, { month: 'Aug', submitted: 116, approved: 94 }, { month: 'Sep', submitted: 139, approved: 107 }];

export function LandTypeChart() { return <div className="chart-flex"><div className="donut-chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={landTypes} dataKey="value" innerRadius={48} outerRadius={68} paddingAngle={3} stroke="none">{landTypes.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip formatter={(value) => [`${value}%`, 'Share']} /></PieChart></ResponsiveContainer><div className="donut-center"><strong>12.4k</strong><small>PARCELS</small></div></div><div className="chart-legend">{landTypes.map((item) => <div key={item.name}><i style={{ background: item.color }} /><span>{item.name}</span><strong>{item.value}%</strong></div>)}</div></div>; }

export function ApplicationsChart() { return <ResponsiveContainer width="100%" height={220}><AreaChart data={months} margin={{ top: 8, right: 5, bottom: 0, left: -18 }}><defs><linearGradient id="submittedFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3c7da3" stopOpacity={0.18} /><stop offset="95%" stopColor="#3c7da3" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#edf0f2" vertical={false} /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: '#8995a1', fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: '#8995a1', fontSize: 11 }} /><Tooltip /><Area type="monotone" dataKey="submitted" stroke="#3c7da3" strokeWidth={2.4} fill="url(#submittedFill)" /><Area type="monotone" dataKey="approved" stroke="#4d9a79" strokeWidth={2.2} fill="transparent" /></AreaChart></ResponsiveContainer>; }

export function StatusBars() { const values = [{ label: 'Submitted', value: 38, color: '#6797b0' }, { label: 'Under review', value: 26, color: '#d3a04d' }, { label: 'Approved', value: 24, color: '#58a27c' }, { label: 'Returned', value: 12, color: '#c87a6d' }]; return <ResponsiveContainer width="100%" height={205}><BarChart data={values} layout="vertical" margin={{ top: 0, right: 20, bottom: 0, left: 0 }}><CartesianGrid stroke="#edf0f2" horizontal={false} /><XAxis type="number" hide /><YAxis dataKey="label" type="category" axisLine={false} tickLine={false} tick={{ fill: '#657381', fontSize: 11 }} width={90} /><Tooltip /><Bar dataKey="value" radius={[0, 4, 4, 0]} barSize={13}>{values.map((item) => <Cell key={item.label} fill={item.color} />)}</Bar></BarChart></ResponsiveContainer>; }
