import { ArrowUpRight, Layers2, MapPinned, RotateCcw, Search, SlidersHorizontal } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import ParcelMap from '../../components/maps/ParcelMap';
import { Badge, Button, Card } from '../../components/ui';

export default function MapPage() {
  const [query, setQuery] = useState('');
  const [visibleLayers, setVisibleLayers] = useState(['Agricultural', 'Residential', 'Commercial', 'Industrial', 'Government']);
  const toggleLayer = (name) => setVisibleLayers((current) => current.includes(name) ? current.filter((layer) => layer !== name) : [...current, name]);
  return <div className="map-page"><div className="map-page-heading"><div><span className="eyebrow">SPATIAL LAND INTELLIGENCE</span><h1>Parcel map</h1><p>Explore cadastral parcels and land record indicators.</p></div><div className="map-page-actions"><Badge tone="green"><span className="live-dot" /> LIVE GIS LAYER</Badge><Button variant="outline" icon={RotateCcw}>Reset view</Button></div></div><Card className="gis-toolbar"><div className="gis-search"><Search size={16} /><input placeholder="Search ULPIN, owner or survey number" value={query} onChange={(event) => setQuery(event.target.value)} /><kbd>⌘ K</kbd></div><span className="gis-toolbar-divider" /><button><Layers2 size={16} /> Layers <span className="layer-count">4</span></button><button><SlidersHorizontal size={16} /> Filters</button><div className="gis-toolbar-right"><span><i className="live-dot" /> Khunti district</span><span className="gis-zoom-label">Zoom 11</span></div></Card><div className="gis-workspace"><div className="gis-map-column"><ParcelMap full visibleLayers={visibleLayers} /><div className="map-bottom-legend"><strong>PARCEL STATUS</strong><span><i className="legend-verified" /> Verified</span><span><i className="legend-pending" /> Pending review</span><span><i className="legend-risk" /> Elevated risk</span><span><i className="legend-dispute" /> Disputed</span></div></div><aside className="gis-side-panel"><div className="gis-panel-head"><div><span className="eyebrow">DISTRICT OVERVIEW</span><h2>Khunti, Jharkhand</h2></div><button className="icon-button"><SlidersHorizontal size={17} /></button></div><div className="gis-summary-stats"><div><small>PARCELS IN VIEW</small><strong>2,184</strong><span>Active dataset</span></div><div><small>NEEDS REVIEW</small><strong className="text-amber">18</strong><span>Across visible area</span></div></div><div className="gis-filter-list"><span className="eyebrow">LAND-USE LAYERS</span>{[['Agricultural', '2,104', '#428c6e'], ['Residential', '426', '#6089ad'], ['Commercial', '82', '#d09a4e'], ['Industrial', '31', '#9f81b2'], ['Government', '64', '#7a8ba0']].map(([name, count, color]) => <label key={name}><input type="checkbox" checked={visibleLayers.includes(name)} onChange={() => toggleLayer(name)} /><i style={{ background: color }} /><span>{name}</span><small>{count}</small></label>)}</div><div className="gis-filter-list risk-layers"><span className="eyebrow">REVIEW LAYERS</span>{[['Disputed parcels', '#8269b6'], ['Possible encroachment', '#c88351'], ['Elevated risk', '#c95c57'], ['Flood risk zone', '#5f9cb0']].map(([name, color], index) => <label key={name}><input type="checkbox" defaultChecked={index < 2} /><i style={{ background: color }} /><span>{name}</span></label>)}</div><div className="gis-panel-note"><MapPinned size={15} /><span>Boundary data represents surveyed or legally verified parcel lines.</span></div><Link className="gis-profile-link" to="/search">Search all land records <ArrowUpRight size={15} /></Link></aside></div></div>;
}
